### ISSUE TITLE
NullPointerException: null - loadManager()

### ISSUE THREAD

**Issue by TptMike** [Everneth/EMI#39]
at com.everneth.emi.ReportManager.loadManager(ReportManager.java:177) ~[?:?]
	at com.everneth.emi.EMI.onEnable(EMI.java:70) ~[?:?]

Either not handling null columns in rows or mishandling an empty result set.

**Comment by TptMike** [comment]
**NOTE:** Until this is fixed, EMI can NOT launch. EMI-RP cannot launch due to being dependent on this one.
